fix minimal dependency version compile error in test
With:
```toml
[dev-dependencies]
criterion = "0.3"
```

The build suddenly fails with

```
Error:   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.6.0/src/lib.rs:34:6
   |
34 |     }
   |      ^ missing tokens in macro arguments

error: could not compile `crossbeam-utils` due to previous error
Error: warning: build failed, waiting for other jobs to finish...
Error: The process '/home/runner/.cargo/bin/cargo' failed with exit code 101
```

Bumping to "0.3.1" fixes this